export * from './homePage/homePage'
export * from './share-deal/share-deal'
export * from './login/login'
export * from './camera/camera'
export * from './deals/deals'
export * from './settings/settings'